### ISSUE TITLE
License document

### ISSUE THREAD

**Issue by Kandy16** [request/caseless#21]
Hey,
 Thanks for the good effort in building this library. We would like to use your node in our project. 

Can you let us know what BSD License have been assigned to this library?

Thanks
Kandy

**Comment by Kandy16** [comment]
Hey Everyone,

We have built a commercial application using your node and have hold our release because of the lack of license information of this particular module. There is a bit of urgency and pressure on us to make the release.

I request you to reveal the license information as soon as possible which will be very helpful for us.

Thanks In Advance
Kandy

**Comment by nylen** [comment]
I personally don't care which BSD license `caseless` uses.  I'll accept a PR as follows:

- `package.json` uses a BSD license ID from https://spdx.org/licenses/
- The license is OSI-approved
- The corresponding license text is included in the repo

As a bonus, that will close out #5 and #16.

**Comment by mikeal** [comment]
please use Apache2 everywhere. it's the BSD license plus some great patent protections and what is basically a "builtin" DCO.

**Comment by vikramarjun** [comment]
Thank you.. We will work on it and submit a pull request shortly. We will be using "Apache-2" license please let us that if you think otherwise.

**Comment by ganeshkumar1989** [comment]
We have added the license info to the package and have created a pull request for the the same. Can you please merge it?

Thank and Regards,
Ganesh Kumar
