### ISSUE TITLE
swap function removes the header if already exists

### ISSUE THREAD

**Issue by XVincentX** [request/caseless#24]
Hello!
When using `swap` function, if casing of passed argument matches the current header, it simply gets removed. It is very easy to reproduce

``` coffeescript
  options.headers = {'Content-Type':'something'}
  normalizedHeaders = caseless options.headers
  normalizedHeaders.swap 'Content-Type'
```

Content-Type is now vanished.

[Ref line](https://github.com/request/caseless/blob/master/index.js#L41)

**Comment by ttahmouch** [comment]
PR #25 .

**Comment by XVincentX** [comment]
This has been fixed!
