### ISSUE TITLE
release 0.9.0 removed and making automated build fail

### ISSUE THREAD

**Issue by sebasrodriguez** [request/caseless#27]
Was version 0.9.0 removed for some particular reason? 

Our CI environment is failing when installing 0.9.0. 

Caseless is a dependency of jspm-github making jspm builds failing.

**Comment by simov** [comment]
Works on my end. Also I don't think it's possible to remove any package or version any more (after lef-pad).

**Comment by sebasrodriguez** [comment]
did you try cleaning the npm cache?

**Comment by simov** [comment]
Actually no, but I'm pretty sure I didn't had `caseless@0.9.0` prior that.

**Comment by sebasrodriguez** [comment]
This returns 502

https://registry.npmjs.org/caseless/-/caseless-0.9.0.tgz

While other versions like 0.10.0 downloads the file

https://registry.npmjs.org/caseless/-/caseless-0.10.0.tgz

**Comment by simov** [comment]
```
req HEAD https://registry.npmjs.org/caseless/-/caseless-0.9.0.tgz
    Host: registry.npmjs.org
res 200 OK
    server:                       nginx/1.4.6 (Ubuntu)
    content-type:                 application/octet-stream
    last-modified:                Mon, 04 Jan 2100 13:43:46 GMT
    etag:                         "f48b0c92-707"
    expires:                      Wed, 06 Jul 2016 02:26:08 GMT
    access-control-allow-origin:  *
    access-control-allow-methods: GET
    cache-control:                max-age=21600
    content-length:               1799
    accept-ranges:                bytes
    date:                         Wed, 06 Jul 2016 15:17:27 GMT
    via:                          1.1 varnish
    age:                          2865
    connection:                   close
    x-served-by:                  cache-lhr6322-LHR
    x-cache:                      HIT
    x-cache-hits:                 1
    x-timer:                      S1467818247.419864,VS0,VE0

```

**Comment by sebasrodriguez** [comment]
Thanks for checking this @simov 

Now I get also a 200 response. Probably there was a problem with the npm registry. 

Closing the issue.
